// Liste centrale des jeux, partagée entre main.js (accueil) et admin.js
// (panneau admin) pour éviter d'avoir deux listes à maintenir en double.
const GAMES = [
  { id: "memory", icon: "🧠", entry: "./games/memory-select.html",
    fr: { name: "Memory", desc: "Trouve toutes les paires" }, en: { name: "Memory", desc: "Find all the pairs" } },
  { id: "tictactoe", icon: "❌⭕",
    fr: { name: "Tic Tac Toe", desc: "Bats l'IA ou ton ami" }, en: { name: "Tic Tac Toe", desc: "Beat the AI or a friend" } },
  { id: "flappy", icon: "🐤",
    fr: { name: "Flappy Bird", desc: "Évite les obstacles" }, en: { name: "Flappy Bird", desc: "Avoid the obstacles" } },
  { id: "sudoku", icon: "🔢",
    fr: { name: "Sudoku", desc: "Résous la grille" }, en: { name: "Sudoku", desc: "Solve the grid" } },
  { id: "pendu", icon: "🪢",
    fr: { name: "Pendu", desc: "Découvre le mot lettre par lettre" }, en: { name: "Hangman", desc: "Guess the word letter by letter" } },
  { id: "mastermind", icon: "🎯",
    fr: { name: "Mastermind", desc: "Devine la combinaison de couleurs" }, en: { name: "Mastermind", desc: "Guess the color combination" } },
  { id: "2048", icon: "🔢",
    fr: { name: "2048 Lite", desc: "Fusionne les tuiles jusqu'à 2048" }, en: { name: "2048 Lite", desc: "Merge tiles up to 2048" } },
  { id: "labyrinthe", icon: "🌀",
    fr: { name: "Labyrinthe", desc: "Trouve la sortie avant la fin du temps" }, en: { name: "Maze", desc: "Find the exit before time runs out" } },
  { id: "puzzle-glissant", icon: "🧩",
    fr: { name: "Puzzle glissant", desc: "Reconstitue l'image en glissant les pièces" }, en: { name: "Sliding Puzzle", desc: "Rebuild the picture by sliding pieces" } },
  { id: "reaction-tap", icon: "⚡",
    fr: { name: "Reaction Tap", desc: "Clique dès que ça devient vert" }, en: { name: "Reaction Tap", desc: "Tap as soon as it turns green" } },
  { id: "aim-trainer", icon: "🎯",
    fr: { name: "Aim Trainer", desc: "Clique les cibles le plus vite possible" }, en: { name: "Aim Trainer", desc: "Click the targets as fast as possible" } },
  { id: "swipe-runner", icon: "🏃",
    fr: { name: "Swipe Runner", desc: "Esquive les obstacles gauche/droite" }, en: { name: "Swipe Runner", desc: "Dodge obstacles left/right" } },
  { id: "speed-math", icon: "🧮",
    fr: { name: "Speed Math", desc: "Résous des calculs contre le chrono" }, en: { name: "Speed Math", desc: "Solve calculations against the clock" } },
  { id: "catch-the-cube", icon: "🧊",
    fr: { name: "Catch the Cube", desc: "Attrape la mascotte avant qu'elle ne se téléporte" }, en: { name: "Catch the Cube", desc: "Catch the mascot before it teleports" } },
  { id: "snake", icon: "🐍",
    fr: { name: "Snake", desc: "Mange les pommes sans te mordre" }, en: { name: "Snake", desc: "Eat apples without biting yourself" } },
  { id: "breakout", icon: "🧱",
    fr: { name: "Breakout", desc: "Détruis toutes les briques avec la balle" }, en: { name: "Breakout", desc: "Destroy all the bricks with the ball" } },
  { id: "space-shooter", icon: "🚀",
    fr: { name: "Space Shooter", desc: "Esquive et tire sur les ennemis" }, en: { name: "Space Shooter", desc: "Dodge and shoot the enemies" } },
  { id: "runner-2d", icon: "🦘",
    fr: { name: "Runner 2D", desc: "Saute par-dessus les obstacles" }, en: { name: "Runner 2D", desc: "Jump over the obstacles" } },
  { id: "mini-tetris", icon: "🧱",
    fr: { name: "Mini-Tetris", desc: "Empile les pièces et complète des lignes" }, en: { name: "Mini-Tetris", desc: "Stack pieces and clear lines" } },
  { id: "trouve-objet", icon: "🔍",
    fr: { name: "Trouve l'objet", desc: "Repère l'objet différent dans la grille" }, en: { name: "Spot It", desc: "Spot the different object in the grid" } },
  { id: "color-match", icon: "🎨",
    fr: { name: "Color Match", desc: "Choisis la nuance exacte" }, en: { name: "Color Match", desc: "Pick the exact shade" } },
  { id: "symetrie", icon: "🦋",
    fr: { name: "Symétrie", desc: "Dis si la forme est symétrique" }, en: { name: "Symmetry", desc: "Say if the shape is symmetrical" } },
  { id: "memory-duo", icon: "🧠",
    fr: { name: "Memory Duo+", desc: "Un memory dont les cartes bougent" }, en: { name: "Memory Duo+", desc: "A memory game where cards move" } },
  { id: "bon-pixel", icon: "🖼️",
    fr: { name: "Bon pixel", desc: "Devine l'image pixelisée" }, en: { name: "Pixel Guess", desc: "Guess the pixelated picture" } },
  { id: "anagrammes", icon: "🔤",
    fr: { name: "Anagrammes", desc: "Remets les lettres dans le bon ordre" }, en: { name: "Anagrams", desc: "Put the letters back in order" } },
  { id: "mot-flash", icon: "⚡",
    fr: { name: "Mot Flash", desc: "Trouve le mot à partir d'un indice" }, en: { name: "Word Flash", desc: "Find the word from a clue" } },
  { id: "lettre-manquante", icon: "🔡",
    fr: { name: "Lettre manquante", desc: "Complète le mot" }, en: { name: "Missing Letter", desc: "Complete the word" } },
  { id: "mini-wordle", icon: "🟩",
    fr: { name: "Mini-Wordle", desc: "Devine le mot de 4 lettres en 5 essais" }, en: { name: "Mini-Wordle", desc: "Guess the 4-letter word in 5 tries" } },
  { id: "mini-othello", icon: "⚫",
    fr: { name: "Mini-Othello", desc: "Retourne les pions de ton adversaire" }, en: { name: "Mini-Othello", desc: "Flip your opponent's pieces" } },
  { id: "connect4-lite", icon: "🔴",
    fr: { name: "Connect 4 Lite", desc: "Aligne 4 pions avant le bot" }, en: { name: "Connect 4 Lite", desc: "Line up 4 pieces before the bot" } },
  { id: "hexa-path", icon: "🔷",
    fr: { name: "Hexa-Path", desc: "Relie les deux côtés du plateau hexagonal" }, en: { name: "Hexa-Path", desc: "Connect both sides of the hex board" } },
  { id: "drapeaux", icon: "🚩",
    fr: { name: "Drapeaux du Monde", desc: "Devine le pays à partir de son drapeau" }, en: { name: "World Flags", desc: "Guess the country from its flag" } },
  { id: "autour-du-monde", icon: "🌍",
    fr: { name: "Autour du Monde", desc: "Devine le pays à partir d'une carte postale" }, en: { name: "Around the World", desc: "Guess the country from a postcard" } },
  { id: "zoom-animal", icon: "🔍",
    fr: { name: "Zoom Animal", desc: "Devine l'animal avant le dézoom complet" }, en: { name: "Zoom Animal", desc: "Guess the animal before it fully zooms out" } },
  { id: "cri-animal", icon: "🔊",
    fr: { name: "Cri d'Animal", desc: "Devine l'animal à partir de son cri" }, en: { name: "Animal Sounds", desc: "Guess the animal from its sound" } },
  { id: "color-switch", icon: "🎡",
    fr: { name: "Color Switch", desc: "Passe par la bonne couleur en sautant" }, en: { name: "Color Switch", desc: "Jump through the matching color" } },
  { id: "water-sort", icon: "💧",
    fr: { name: "Tri de l'Eau", desc: "Trie les couleurs dans les bons tubes" }, en: { name: "Water Sort", desc: "Sort the colors into the right tubes" } },
  { id: "flow-free", icon: "🌈",
    fr: { name: "Flow Libre", desc: "Relie les ronds de même couleur sans croiser les tuyaux" }, en: { name: "Flow Free", desc: "Connect matching dots without crossing pipes" } },
  { id: "stack-tower", icon: "🧱",
    fr: { name: "Stack Tower", desc: "Empile les blocs le plus haut possible" }, en: { name: "Stack Tower", desc: "Stack the blocks as high as possible" } },
  { id: "piano-tiles", icon: "🎹",
    fr: { name: "Piano Tiles", desc: "Touche les tuiles noires sans en rater une" }, en: { name: "Piano Tiles", desc: "Tap the black tiles without missing one" } },
  { id: "air-hockey", icon: "🏒",
    fr: { name: "Air Hockey", desc: "Marque plus de buts que le bot" }, en: { name: "Air Hockey", desc: "Score more goals than the bot" } },
  { id: "devine-artiste", icon: "🖌️",
    fr: { name: "Devine l'Artiste", desc: "Reconnais le peintre ou le musicien sur la photo" }, en: { name: "Guess the Artist", desc: "Recognize the painter or musician in the photo" } },
  { id: "chef-doeuvre", icon: "🖼️",
    fr: { name: "Chef-d'Œuvre", desc: "Devine qui a créé cette œuvre d'art" }, en: { name: "Masterpiece", desc: "Guess who created this artwork" } },
  { id: "blind-test", icon: "🎧",
    fr: { name: "Blind Test", desc: "Écoute l'extrait et devine la chanson" }, en: { name: "Blind Test", desc: "Listen to the clip and guess the song" } },
  { id: "complete-citation", icon: "💬",
    fr: { name: "Complète la Citation", desc: "Choisis la bonne suite de la phrase" }, en: { name: "Finish the Line", desc: "Pick the right ending to the phrase" } }
];

const GAMES_BY_ID = Object.fromEntries(GAMES.map(g => [g.id, g]));

function entryFor(game) {
  return game.entry || `./games/${game.id}.html`;
}
